"""empty message

Revision ID: 57e0c1863ef8
Revises: f5ec37b793d5
Create Date: 2021-09-09 16:25:53.960037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57e0c1863ef8'
down_revision = 'f5ec37b793d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'article_category', ['category_id'], ['id'])
    op.drop_column('article', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
